// Generated by gencpp from file test_msgs/my_file.msg
// DO NOT EDIT!


#ifndef TEST_MSGS_MESSAGE_MY_FILE_H
#define TEST_MSGS_MESSAGE_MY_FILE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_msgs
{
template <class ContainerAllocator>
struct my_file_
{
  typedef my_file_<ContainerAllocator> Type;

  my_file_()
    : robot_igite_academy(0.0)  {
    }
  my_file_(const ContainerAllocator& _alloc)
    : robot_igite_academy(0.0)  {
  (void)_alloc;
    }



   typedef float _robot_igite_academy_type;
  _robot_igite_academy_type robot_igite_academy;





  typedef boost::shared_ptr< ::test_msgs::my_file_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_msgs::my_file_<ContainerAllocator> const> ConstPtr;

}; // struct my_file_

typedef ::test_msgs::my_file_<std::allocator<void> > my_file;

typedef boost::shared_ptr< ::test_msgs::my_file > my_filePtr;
typedef boost::shared_ptr< ::test_msgs::my_file const> my_fileConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_msgs::my_file_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_msgs::my_file_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'test_msgs': ['/home/sihc/catkin_ws/src/test_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::my_file_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::my_file_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::my_file_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::my_file_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::my_file_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::my_file_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_msgs::my_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "069c9e64d21688e60165de9024f3f89c";
  }

  static const char* value(const ::test_msgs::my_file_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x069c9e64d21688e6ULL;
  static const uint64_t static_value2 = 0x0165de9024f3f89cULL;
};

template<class ContainerAllocator>
struct DataType< ::test_msgs::my_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_msgs/my_file";
  }

  static const char* value(const ::test_msgs::my_file_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_msgs::my_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 robot_igite_academy\n\
";
  }

  static const char* value(const ::test_msgs::my_file_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_msgs::my_file_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_igite_academy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_file_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_msgs::my_file_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_msgs::my_file_<ContainerAllocator>& v)
  {
    s << indent << "robot_igite_academy: ";
    Printer<float>::stream(s, indent + "  ", v.robot_igite_academy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MSGS_MESSAGE_MY_FILE_H
