// Generated by gencpp from file traffic_sign/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_MESSAGE_ADDTWOINTS_H
#define TRAFFIC_SIGN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <traffic_sign/AddTwoIntsRequest.h>
#include <traffic_sign/AddTwoIntsResponse.h>


namespace traffic_sign
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace traffic_sign


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traffic_sign::AddTwoInts > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::traffic_sign::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::traffic_sign::AddTwoInts > {
  static const char* value()
  {
    return "traffic_sign/AddTwoInts";
  }

  static const char* value(const ::traffic_sign::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::traffic_sign::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::traffic_sign::AddTwoInts > 
template<>
struct MD5Sum< ::traffic_sign::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign::AddTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign::AddTwoIntsRequest> should match 
// service_traits::DataType< ::traffic_sign::AddTwoInts > 
template<>
struct DataType< ::traffic_sign::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::traffic_sign::AddTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traffic_sign::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::traffic_sign::AddTwoInts > 
template<>
struct MD5Sum< ::traffic_sign::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign::AddTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign::AddTwoIntsResponse> should match 
// service_traits::DataType< ::traffic_sign::AddTwoInts > 
template<>
struct DataType< ::traffic_sign::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::traffic_sign::AddTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAFFIC_SIGN_MESSAGE_ADDTWOINTS_H
