// Generated by gencpp from file traffic_sign/BadTwoInts.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_MESSAGE_BADTWOINTS_H
#define TRAFFIC_SIGN_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <traffic_sign/BadTwoIntsRequest.h>
#include <traffic_sign/BadTwoIntsResponse.h>


namespace traffic_sign
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace traffic_sign


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traffic_sign::BadTwoInts > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::traffic_sign::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::traffic_sign::BadTwoInts > {
  static const char* value()
  {
    return "traffic_sign/BadTwoInts";
  }

  static const char* value(const ::traffic_sign::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::traffic_sign::BadTwoIntsRequest> should match 
// service_traits::MD5Sum< ::traffic_sign::BadTwoInts > 
template<>
struct MD5Sum< ::traffic_sign::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign::BadTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign::BadTwoIntsRequest> should match 
// service_traits::DataType< ::traffic_sign::BadTwoInts > 
template<>
struct DataType< ::traffic_sign::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::traffic_sign::BadTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traffic_sign::BadTwoIntsResponse> should match 
// service_traits::MD5Sum< ::traffic_sign::BadTwoInts > 
template<>
struct MD5Sum< ::traffic_sign::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign::BadTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign::BadTwoIntsResponse> should match 
// service_traits::DataType< ::traffic_sign::BadTwoInts > 
template<>
struct DataType< ::traffic_sign::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::traffic_sign::BadTwoInts >::value();
  }
  static const char* value(const ::traffic_sign::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAFFIC_SIGN_MESSAGE_BADTWOINTS_H
