// Generated by gencpp from file traffic_sign/BadTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_MESSAGE_BADTWOINTSRESPONSE_H
#define TRAFFIC_SIGN_MESSAGE_BADTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traffic_sign
{
template <class ContainerAllocator>
struct BadTwoIntsResponse_
{
  typedef BadTwoIntsResponse_<ContainerAllocator> Type;

  BadTwoIntsResponse_()
    {
    }
  BadTwoIntsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BadTwoIntsResponse_

typedef ::traffic_sign::BadTwoIntsResponse_<std::allocator<void> > BadTwoIntsResponse;

typedef boost::shared_ptr< ::traffic_sign::BadTwoIntsResponse > BadTwoIntsResponsePtr;
typedef boost::shared_ptr< ::traffic_sign::BadTwoIntsResponse const> BadTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traffic_sign

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'traffic_sign': ['/home/sihc/catkin_ws/src/traffic_sign/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_sign/BadTwoIntsResponse";
  }

  static const char* value(const ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BadTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::traffic_sign::BadTwoIntsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_SIGN_MESSAGE_BADTWOINTSRESPONSE_H
