// Generated by gencpp from file traffic_sign/traffic_sign_msg.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_MESSAGE_TRAFFIC_SIGN_MSG_H
#define TRAFFIC_SIGN_MESSAGE_TRAFFIC_SIGN_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traffic_sign
{
template <class ContainerAllocator>
struct traffic_sign_msg_
{
  typedef traffic_sign_msg_<ContainerAllocator> Type;

  traffic_sign_msg_()
    : traffic_sign_type(0)  {
    }
  traffic_sign_msg_(const ContainerAllocator& _alloc)
    : traffic_sign_type(0)  {
  (void)_alloc;
    }



   typedef int64_t _traffic_sign_type_type;
  _traffic_sign_type_type traffic_sign_type;





  typedef boost::shared_ptr< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> const> ConstPtr;

}; // struct traffic_sign_msg_

typedef ::traffic_sign::traffic_sign_msg_<std::allocator<void> > traffic_sign_msg;

typedef boost::shared_ptr< ::traffic_sign::traffic_sign_msg > traffic_sign_msgPtr;
typedef boost::shared_ptr< ::traffic_sign::traffic_sign_msg const> traffic_sign_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_sign::traffic_sign_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traffic_sign

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'traffic_sign': ['/home/sihc/catkin_ws/src/traffic_sign/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b39d3b00117d7861701b14c6e1e0db30";
  }

  static const char* value(const ::traffic_sign::traffic_sign_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb39d3b00117d7861ULL;
  static const uint64_t static_value2 = 0x701b14c6e1e0db30ULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_sign/traffic_sign_msg";
  }

  static const char* value(const ::traffic_sign::traffic_sign_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 traffic_sign_type\n\
";
  }

  static const char* value(const ::traffic_sign::traffic_sign_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traffic_sign_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traffic_sign_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_sign::traffic_sign_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_sign::traffic_sign_msg_<ContainerAllocator>& v)
  {
    s << indent << "traffic_sign_type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.traffic_sign_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_SIGN_MESSAGE_TRAFFIC_SIGN_MSG_H
